### ISSUE TITLE
voting - open or closed ballot 

### ISSUE THREAD

**Issue by binarytemple** [TI-Tokyo/riak-community-admin#14]
Is the voting system going to be an open or closed ballot?

**Comment by gpad** [comment]
I think that all the procedure and the counting of the votes should be public but every single vote should be secret.

**Comment by binarytemple** [comment]
That would be ideal, I also feel that way. However I can't think of a way to do it. Can you or anyone else suggest a means to achieve this (considering that a paper ballot is not an option).

**Comment by Licenser** [comment]
absolutely closed
