### ISSUE TITLE
Is this what  b365 is actually looking for?

### ISSUE THREAD

**Issue by sata** [TI-Tokyo/riak-community-admin#15]
From the RIAK Roadmap Workshop[1] 

> Governance?
How are we to manage the project going forward? Our feeling is we do not need a formal body as being discussed in the slack group. We see the project going forward as a simple repo into which likeminded developers agree and contribute changes. Placing overbearing procedure and structure on what is currently a small community will dissuade other from joining and contributing.

Personally I don't think it's possible to achieve such a goals without having a organizational structure to serve the common goal of making Riak a more stable product. But I do feel Andy has a point and the whole setup of DG, RMG, PDG, AG etc - is this really necessary? Where does this structure come from?

Also, if  it doesn't align with what Bet365 has in mind, how much credibility does this work have? We need to make sure that Bet365 is on board with this otherwise it's not going to be a fruitful result given they will have the control of supporting or not supporting this.  

[1] http://lists.basho.com/pipermail/riak-users_lists.basho.com/2017-September/019534.html

**Comment by pjaclark** [comment]
There needs to be a single source for releases and roadmap management. Bet365 have said it's not going to be them.

The structure is actually quite light, as most of it comes down to once a month online meetings to discuss the roadmap (the Project Direction Group), and the Development Group is self-managing. The Release Group is just there to ensure that high-quality, stable releases happen - and is run by the Developers. The Admin Group provides all the other random bits and bobs like paying invoices and running servers (like the docs and file stores) for everyone to use. The voting stuff is to ensure that no single group hijacks the project, and even that is as light as possible.

Writing this document is a living, collaborative process. If you have thoughts and suggestions for improvements (or even large changes), I would love to hear them. If Bet365 have an alternate proposal that guarantees a stable platform for users, we would be happy to adopt it or take the key ideas from it.

Without a structure, things get missed and trust is lowered. If someone is going to be investing $1m+ in servers and infrastructure for a Riak cluster for business critical systems, they want to know the software is being written and managed safely. They want to know upgrades won't break everything. Without a coherent group willing to say "this is the official release of `Riak KV 2.4.1`" they won't get that and will leave for other platforms.

On a more personal note, as a support provider for Riak it is much harder to provide support if there are multiple forks with conflicting code and documentation. We can't say, for example, that we support Riak KV 2.4.1 if we don't know which Riak 2.4.1 they mean!

**Comment by pjaclark** [comment]
Decisions from 2017-09-29:

- For the time being, continue as planned with setting up the group.
- Hope to merge Github/Kyorai back into GitHub/Basho and use that as the canonical source.
- If unable to use Github/Basho then use Github/Kyorai as the canonical source.
