### ISSUE TITLE
Send weekly meeting invites by email to the riak-users list

### ISSUE THREAD

**Issue by ghost** [TI-Tokyo/riak-community-admin#25]
It's good to get new people involved and good to keep those currently involved regularly reminded of when meetings are happening. I suggest the following : 

* Create the channel for the following weeks event
* Copy the link 
* Create an event in Google calendar 
* Download the ical file 
* Email it to the riak-users mailing list 

Now everyone has:

* The time of the event - adjusted to their own timezone
* A reminder, presumably

Or is this idea totally stupid/objectionable ? 

<img width="784" alt="screen shot 2017-10-26 at 16 10 54" src="https://user-images.githubusercontent.com/31992054/32061525-c33d2dba-ba69-11e7-9ac7-ce11ff3fc735.png">

**Comment by smarj** [comment]
+1
