### ISSUE TITLE
 riak/hyper - suggestion/open the debate to remove it

### ISSUE THREAD

**Issue by ghost** [TI-Tokyo/riak-community-admin#26]
Who actually uses it, like anyone? It’s been a PITA to deal with (licensing, compatibility, divergence between basho version and upstream) and I just wonder if anyone uses it or will ever be willing to maintain it - also it’s got a load of c code which makes me nervous - interested in feedback.

**Comment by jadeallenx** [comment]
What's the compatibility issue?

I don't have a strong opinion either way but I guess if I had to choose an option, I'd opt for removing it.

**Comment by ghost** [comment]
@mrallen1  Upstream is 17+ only

**Comment by jadeallenx** [comment]
Because it supports maps I suppose.
