### ISSUE TITLE
Eligibility for PG votes

### ISSUE THREAD

**Issue by Licenser** [TI-Tokyo/riak-community-admin#3]
The proposed requirements to vote on Project Direction Group - End users are stated as:

`All companies supporting the project through resources or financing`

This opens the possibility for abuse and cluttering.

Abuse of this rule can happen by a bad actor creating many micro supports and gaining voiting rights.

Cluttering can happen over time as only a single support action has to be taken for gaining a indefinite voting right, this will mean that we might need to contact companies or individuals that are no longer active or interested in the community.

I would propose two restrictions:

1) A minimum 'amount' of support
2) A time limit (as in within the prior period)

**Comment by Licenser** [comment]
The development group specifies a 6 month period for activity. I think it would be sensible to apply the same time frame here.

**Comment by pjaclark** [comment]
The time limit sounds sensible - 6 months prior to an election being called makes sense to me.

The minimum amount of support also makes sense, but I have no idea how to quantify this. Cash? Resources like servers or bandwidth? Developer time? Donation of code? It seems very fluffy, so I would suggest just going to with any contribution on a corporate level (i.e. not just that someone who works for the company decided to help out as an individual on their own time).

I've changed it to this in the meantime:

```
#### Project Direction Group
* All members of the Development Group will get 1 vote for the Developer positions.
* All companies supporting the project through resources or financing in the 6 months prior to an election being called will get 1 vote for the End-User positions.
* All members of the Admin Group will get 1 vote for the Admin position.
```

**Comment by pjaclark** [comment]
From Meeting on 2017-09-01 - idea of scaling membership for end-users based on the resource/cash they donate ala CNCF (https://www.cncf.io/about/join/).

Have cheap-tier that allows voting, and higher tier that allows you to run for a seat.

**Comment by Licenser** [comment]
I'd disagree with the 'allow run for a seat' part, given it might disqualify good people just because their company doesn't meet the requirements.

My understanding the end-user group's purpose is to make the project usable from a user perspective. An outsider that is agreed on by many companies but not part of any is a possible situation.

Keeping the electability open (even to people who never donated) but not the right to elect promotes that the people in the PG are of high quality, and those who define 'quality' are those who are contributing to riaks continued existence.

**Comment by pjaclark** [comment]
Decisions from 2017-09-08:

- Have scaling end-user memberships.
- All end-users get 1 vote.
- All higher-level end-users can nominate someone as a Candidate.
- All conflicts of interest must be made public.
- The PDG can raise issues, and if needed remove members by the already established mechanisms.
- The PDG can nominate Candidates to ensure there are at least 1 more Candidates than positions available.

**Comment by pjaclark** [comment]
Update from 2017-09-08:

- Have scaling end-user memberships.
- All end-users get 1 vote.
- All higher-level end-users can nominate someone as a Candidate.
- All conflicts of interest must be made public.
- The PDG can raise issues, and if needed remove members by the already established mechanisms.
- The PDG can nominate Candidates to ensure there is at least 1 more Candidate than positions available, and can always nominate 1 extra Candidate.
