### ISSUE TITLE
We are lacking a change process for the governing rules

### ISSUE THREAD

**Issue by Licenser** [TI-Tokyo/riak-community-admin#6]
We do not specify any process of approving changes to the governing rules and process. This includes rules for the 1st approval of our results.

I would propose the following rules:

General changes can be proposed by any PG member and are considered when seconded by at least one other person.

To pass a change to the governance process (this document) a 3/4 majority of the PG is required (which means 9 yes votes).

If a change impacts a single working group, the group in question can veto a change with an absolute majority 50% of members (not 50% of voting members).

Changes that only affect a single team can be decided by the team in question with a 3/4 majority. the PG can veto those changes with an absolute 50% majority.

**Comment by pjaclark** [comment]
Safer to say "more than 75%" than "3/4 majority" for weird edge cases.

Aside from that, I agree with you in that we need a process, and your process seems logical in the most part. It has to be a majority of "voting eligible members" to stop people no longer involved in the community stopping change.

I've added this to get the discussion going:

```### Process to change the Community's governance structure or processes

#### General Changes
General changes to the Community's governance structure or processes can be proposed by any project member to the Project Direction Group via the Admin Group's Feedback Team. 

A Project Direction Group member must sponsor a proposal and it must be seconded by another member to then go to a vote of all members. 

The vote is passed with a majority vote of more than 75% of the members of the Project Direction Group. 

This result can be contested by a group consisting of more than 10% of the voting eligible members of the Community, which will lead to a Community-wide referendum held by the same rules as an election.

#### Group-level Changes
Changes that apply to only one Group can be contested by a group consisting of more than 10% of the voting eligible members of the Group in question, which will lead to a Group-wide referendum held by the same rules as an election.

#### Team-level Changes
A Team can change it's internal processes with a majority vote of more than 75% of the eligible voters.

The Project Direction Group can veto the changes voted at on the Team level with a majority vote of more than 50% of the Project Direction Group members.```

**Comment by pjaclark** [comment]
Decisions from 2017-09-08:

Use this text.
