### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by pjaclark** [TI-Tokyo/riak-community-admin#7]
Copy from Slack.

Code of Conduct
--------------------
Taken from #general discussions between @heinz and @kunthar earlier today.

Sample CoC from other projects:

Ubuntu
https://www.ubuntu.com/about/about-ubuntu/conduct

Python
https://www.python.org/psf/codeofconduct/

FreeBSD
https://www.freebsd.org/internal/code-of-conduct.html

Postgres
https://wiki.postgresql.org/wiki/Code_of_Conduct

Project-Fifo (@heinz's project)
https://project-fifo.net/coc.html

The thoughts so far is that short and simple is better for the time being. That would make the CoC from Python and Project-Fifo the ones to check out first, and Ubuntu's one as rather long and wordy.

Please reply in the thread. (edited)

peterclark [6 days ago] 
I like the short and simple ones, too. We can always change it in the future. For the time being, I'd go for Project Fifo's one as it is very simple, easy to understand and hits all the right notes.

heinz [5 days ago] 
I’m obviously biased on this as I already made the decision for msyself :wink: but I do like the python one as well. (edited)

**Comment by pjaclark** [comment]
Any objections to importing the Python one into the Governance section?

**Comment by Licenser** [comment]
Two of the things I'm personally missing in the Python version:

* the assumption of good faith/intend there was [a nice article on that](https://rakudo.party/post/On-Troll-Hugging-Hole-Digging-and-Improving-Open-Source-Communities#hug2:feedthehandthatbitesyou) (reading the rest is also really worth it as it affectsw us)
* and clear statement against public shaming. We are no longer in the middle agaes where we put people on the pilroy, seeing what happens in many communities lately is in my opinion distasteful and it robs people of the chance to grow and learn.

That said I like the Python one a lot and we are not forced to take it 1:1 verbatim.

note: CoC's are always a very heated topic so please don't take those as the end of all opionons just mine, feel free to disagree ;)

**Comment by pjaclark** [comment]
Both make sense. Something like this? 

Adapted from Python Community Code of Conduct (https://www.python.org/psf/codeofconduct/)

# Riak Community Code of Conduct

The Riak community is made up of members from around the globe with a diverse set of skills, personalities, and experiences. It is through these differences that our community experiences great successes and continued growth. When you're working with members of the community, we encourage you to follow these guidelines which help steer our interactions and strive to keep Riak a positive, successful, and growing community.

A member of the Riak community is:

## Open

Members of the community are open to collaboration, whether it's on Project Direction Group Proposals, patches, problems, or otherwise. We're receptive to constructive comment and criticism, as the experiences and skill sets of other members contribute to the whole of our efforts. We're accepting of all who wish to take part in our activities, fostering an environment where anyone can participate and everyone can make a difference.

## Considerate

Members of the community are considerate of their peers -- other Riak users. We're thoughtful when addressing the efforts of others, keeping in mind that often times the labor was completed simply for the good of the community. We're attentive in our communications, whether in person or online, and we're tactful when approaching differing views. We have a base assumption of good faith and intent in all communications.

## Respectful

Members of the community are respectful. We're respectful of others, their positions, their skills, their commitments, and their efforts. We're respectful of the volunteer efforts that permeate the Riak community. We're respectful of the processes set forth in the community, and we work within them. When we disagree, we are courteous in raising our issues.

When we disagree, we disagree with respect and in public. We do not publically shame people for different opinions or abilities, but seek to find a common opinion and to help others to improve their abilities.

Overall, we're good to each other. We contribute to this community not because we have to, but because we want to. If we remember that, these guidelines will come naturally.

**Comment by pjaclark** [comment]
Decisions from 2017-09-08:

Add this version to the proposal.
