### ISSUE TITLE
How to deal with possible conflicts of interest

### ISSUE THREAD

**Issue by Licenser** [TI-Tokyo/riak-community-admin#8]
I think especially with the riak_core crowd (like me ;)) we have the potential to see quite some situations where there are conflicts of interest and we should possibly clarify how to deal with them.

The reasoning here is that _core is an excellent framework to build databases, so the chances to see some development that partially competes with the riak_* line up is really likely. But it reaches beyond that, also towards conflicts between members.

I will take myself as an example here, not because I think this is something especially affecting me (even so it also affects me) but also because I'd not want to step on someone's toes by using them as an example (I also don't feel qualified to judge possible conflicts on other peoples code).

I think the bare minimum needs to be full disclosure so that when it comes to elections people are aware of connections of the people they vote for. That part seems pretty sensible and straight forward.

It gets more complicated when we are having a more public channel where people ask questions. How do we deal with situations like that, one one hand it feels like the goal should be to provide users the best possible solution, on the other hand, it feels odd to suggest "why not use something else" especially when you have a personal interest in something else?

I've no real solution for that the best idea I came up with so far would be to limit this kind of suggestions to pre-approved comparisons. Taking my own example again, for sake of not making this totally theoretical, I don't think it'd be OK to just go `"Hey try DalmatinerDB instead of RiakTS it's sooo much better."` in a help channel. On the other hand, totally ignoring it isn't really awesome either, users having a bad experience or burrying themselfs in tehcnical debt because they picked a wrong solution doesn't help them. So what I thought if is that when we disclose possible conflicts we also provide a compairison on the conflicting parts and to keep it fair put that under scrutiny by the PG to prevent unrealistic or biased comparisons. That way we could present people with a unbiased information and help them make a choice wtihout either restricting people or creating conflict with the longlivity of the project.

The second possibility for conflects I see between companies (I can't take myself as an example here so my apologies to ESL/TI for using them here). But what happens if say Bob joins the project and also wants to offer suppot for RiakKV. Is it OK for Bob to promote he is offering support in public forums? Is it OK for ELS/TI to do so? Are Bob and ELS/TI forbiddent or requred to mention the other? Is it a first come first serve thing?

Perhaps we should keep a list of members/companies and what their products services are. It does go a bit in the same region as the pre approved compairison.

That would also go a bit towards #3 as we could allow higher tiers to be more prominent on the list (the same way CNCF does) as an incentive.

**Comment by pjaclark** [comment]
Decisions from 2017-09-08:

- Have public who we area / what we do lists for members.
- Have section for showing off services by end-users organised by membership level (then surname. first name, middle names) with links to public projects (GitHub repos, community pages, other URLs).
- Competing services are encouraged, and best features highlighted.
- Competing projects are encouraged, and best features highlighted.
- Candidate information should include their affiliated companies and projects.
