### ISSUE TITLE
Groups and Teams list

### ISSUE THREAD

**Issue by Bob-The-Marauder** [TI-Tokyo/riak-community-admin#9]
In paragraph 3, there is an example stating that
`a Team might deal with writing source code for Riak Core, and would therefore NOT deal with writing source code for Riak KV`
Although I have no problem with this concept, to the casual observer with only light knowledge of Riak (read corporate decision maker), Core is a part of KV and should therefore mean that any changes with Core cause changes in KV therefore changing Core's source code can cause changes in KV's source code, so the Core team is indirectly changing KV's source code ... My head hurts.
Instead of this, recommend two things that are more clearly separated to avoid any risk of confusion at this early point of the document e.g. `CS and KV` or `Core and the Java Client Libraries`

**Comment by pjaclark** [comment]
Decisions from 2017-09-08:

Change phrasing to:

```
Each Group is made up of Teams which deal with specific areas of responsibility and dependant projects do not dictate the development of their dependencies. For example, a Team might deal with writing source code for Riak Core, which may break Riak KV. The Riak KV Team would then be responsible for patching Riak KV. Teams will work together, and membership is intended to be fluid between them.
```
